# change the build directory to be within react's scope
project_structure:
    build: client/src/artifacts

      
# automatically fetch contract sources from Etherscan
autofetch_sources: True
# dotenv: .env


# networks:
#   default: development
#   development:
#     cmd_settings:
#       mnemonic: brownie
#       default_balance: 100000000000000000000
#       unlock: <ACCOUNT ADDRESS HERE> # optionally add saved brownie account to Ganache
#       # (requires explicit transfer of eth to accounts[-1]) 

#     update_interval: 60
#     verify: False
  
#   kovan:

#     verify: False
#     update_interval: 60


# wallets:
#   from_key: ${PRIVATE_KEY}


# enable output of development artifacts to load with react
dev_deployment_artifacts: true


dependencies:
    - uniswap/v2-core@1.0.1
    - uniswap/v2-periphery@1.0.0-beta.0
    - OpenZeppelin/openzeppelin-contracts@4.8.0
    - aave/protocol-v2@1.0

compiler:
    solc:
        remappings:
            - 'uniswap_core=uniswap/v2-core@1.0.1'
            - 'uniswap_periphery=uniswap/v2-periphery@1.0.0-beta.0'
            - 'openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0'
            - 'aave=aave/protocol-v2@1.0'